### ISSUE TITLE
Empty game view

### ISSUE THREAD

**Issue by ar-maged** [EvanBacon/Expo-Crossy-Road#1]
**Problems:**
- The game view is empty except for the score counter
- The app keeps crashing & reloading on losing the game or chicken choosing

**Hardware & Software:**
- Sony Xperia Z3 Dual
- Android `v6.0.1`
- Expo client `v1.16.1`

![screenshot_20170606-233532](https://user-images.githubusercontent.com/11808903/26853680-447a19b8-4b13-11e7-9a22-9ae09b100898.png)

**Comment by ar-maged** [comment]
Before anything though, very nice work on recreating the game with such an impressive set of tools! Hat off to you, sir.

**Comment by EvanBacon** [comment]
@ar-maged thanks so much! I didn't test it on android unfortunately, it runs pretty just barely on an iPhone 7 Plus so my first inclination would be that the gpu cannot handle the overhead. I'll see if I can get it running on Genymotion

**Comment by nikki93** [comment]
D: Yeah I need to test your games on Android and see what's going on @EvanBacon

**Comment by Monte9** [comment]
@EvanBacon I have a Samsung s8 and tested your app on it yesterday. Ran just fine. Although this was the published app on Expo. I haven't tried running it locally from the repo.

**Comment by EvanBacon** [comment]
Fixed when I rewrote it for web
