### ISSUE TITLE
Unable to resolve "./assets/models/environment/grass/0/0.obj" from "Models.js"

### ISSUE THREAD

**Issue by leonlee723** [EvanBacon/Expo-Crossy-Road#10]
Hi EvanBacon
     I try to run the game on android. But no matter macbook or win 10, when I run 'expo start',  'Unable to resolve "./assets/models/environment/grass/0/0.obj" from "Models.js"' be shown on android phone.

**Comment by EvanBacon** [comment]
Fixed the models
