### ISSUE TITLE
How did you make it so that you can install it on chrome?

### ISSUE THREAD

**Issue by stewpidtnlvr** [EvanBacon/Expo-Crossy-Road#20]
How did you make it so that you can install it on chrome? (specifically on a chromebook)

**Comment by RichardLindhout** [comment]
It is inside Expo Web and you can do the same with a service worker. It's called progressive web apps

**Comment by flexbox** [comment]
Just to complete the reference:

>A progressive web app (or PWA for short) is a website that can be installed on the user's device and used offline. If you build your native app with Expo, then Expo CLI can generate a lot of the PWA automatically based on how the native app works.

https://docs.expo.dev/guides/progressive-web-apps/
